<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="my_arm">

  <xacro:arg name="ros2_control_params" default=""/>

  <!-- =========================
       Parameters
       ========================= -->
  <!-- Link lengths (meters) -->
  <xacro:arg name="L1" default="0.12"/>
  <xacro:arg name="L2" default="0.12"/>
  <xacro:arg name="L3" default="0.12"/>

  <!-- Spherical wrist: set these to 0 -->
  <xacro:arg name="L4" default="0.0"/>
  <xacro:arg name="L5" default="0.0"/>
  <xacro:arg name="L6" default="0.0"/>

  <!-- Sizes -->
  <xacro:arg name="r_link" default="0.02"/>
  <xacro:arg name="base_x" default="0.10"/>
  <xacro:arg name="base_y" default="0.10"/>
  <xacro:arg name="base_z" default="0.04"/>

  <!-- Masses (kg) -->
  <xacro:arg name="m_base" default="1.0"/>
  <xacro:arg name="m_link" default="0.3"/>
  <xacro:arg name="m_wrist" default="0.05"/>  <!-- small non-zero mass for wrist links -->

  <!-- Joint limits -->
  <xacro:arg name="joint_vel" default="2.0"/>
  <xacro:arg name="joint_effort" default="5.0"/>

  <!-- Convenience properties -->
  <xacro:property name="L1" value="$(arg L1)"/>
  <xacro:property name="L2" value="$(arg L2)"/>
  <xacro:property name="L3" value="$(arg L3)"/>
  <xacro:property name="r"  value="$(arg r_link)"/>

  <!-- Wrist visualization radius (small spheres) -->
  <xacro:property name="r_wrist" value="${0.5 * $(arg r_link)}"/>

  <!-- =========================
       Inertial macros (Gazebo-safe)
       ========================= -->
  <xacro:macro name="inertial_box" params="mass x y z">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="${mass*(y*y + z*z)/12.0}" ixy="0.0" ixz="0.0"
               iyy="${mass*(x*x + z*z)/12.0}" iyz="0.0"
               izz="${mass*(x*x + y*y)/12.0}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="inertial_cylinder_z" params="mass radius length">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="${mass*(3*radius*radius + length*length)/12.0}" ixy="0.0" ixz="0.0"
               iyy="${mass*(3*radius*radius + length*length)/12.0}" iyz="0.0"
               izz="${mass*(radius*radius)/2.0}"/>
    </inertial>
  </xacro:macro>

  <!-- Simple sphere inertia (non-zero, stable) -->
  <xacro:macro name="inertial_sphere" params="mass radius">
    <inertial>
      <mass value="${mass}"/>
      <!-- I = 2/5 m r^2 -->
      <inertia ixx="${0.4*mass*radius*radius}" ixy="0.0" ixz="0.0"
               iyy="${0.4*mass*radius*radius}" iyz="0.0"
               izz="${0.4*mass*radius*radius}"/>
    </inertial>
  </xacro:macro>

  <!-- =========================
       Materials
       ========================= -->
  <material name="grey"><color rgba="0.6 0.6 0.6 1.0"/></material>
  <material name="dark"><color rgba="0.2 0.2 0.2 1.0"/></material>
  <material name="blue"><color rgba="0.2 0.3 0.8 1.0"/></material>

  <!-- =========================
       Links
       ========================= -->
  <!-- Dummy root link (no inertia) to keep KDL happy -->
  <link name="world"/>

  <joint name="world_to_base" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${$(arg base_z)/2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="$(arg base_x) $(arg base_y) $(arg base_z)"/>
      </geometry>
      <material name="dark"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${$(arg base_z)/2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="$(arg base_x) $(arg base_y) $(arg base_z)"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="$(arg m_base)" x="$(arg base_x)" y="$(arg base_y)" z="$(arg base_z)"/>
  </link>

  <!-- Main arm links as cylinders aligned along +Z -->
  <xacro:macro name="arm_link" params="name length mass mat">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 ${length/2.0}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${r}" length="${length}"/>
        </geometry>
        <material name="${mat}"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${length/2.0}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${r}" length="${length}"/>
        </geometry>
      </collision>
      <xacro:inertial_cylinder_z mass="${mass}" radius="${r}" length="${length}"/>
    </link>
  </xacro:macro>

  <xacro:arm_link name="link1" length="${L1}" mass="$(arg m_link)" mat="grey"/>
  <xacro:arm_link name="link2" length="${L2}" mass="$(arg m_link)" mat="grey"/>
  <xacro:arm_link name="link3" length="${L3}" mass="$(arg m_link)" mat="grey"/>

  <!-- Wrist links: zero-length, just small spheres to visualize axes -->
  <xacro:macro name="wrist_link" params="name mass mat">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${r_wrist}"/>
        </geometry>
        <material name="${mat}"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${r_wrist}"/>
        </geometry>
      </collision>
      <xacro:inertial_sphere mass="${mass}" radius="${r_wrist}"/>
    </link>
  </xacro:macro>

  <xacro:wrist_link name="link4" mass="$(arg m_wrist)" mat="blue"/>
  <xacro:wrist_link name="link5" mass="$(arg m_wrist)" mat="blue"/>
  <xacro:wrist_link name="link6" mass="$(arg m_wrist)" mat="blue"/>

  <!-- =========================
       Joints (6-DOF)
       ========================= -->
  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 $(arg base_z)" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14159" upper="3.14159" effort="$(arg joint_effort)" velocity="$(arg joint_vel)"/>
    <dynamics damping="0.2" friction="0.0"/>
  </joint>

  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${L1}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-3.14159" upper="3.14159" effort="$(arg joint_effort)" velocity="$(arg joint_vel)"/>
    <dynamics damping="0.2" friction="0.0"/>
  </joint>

  <joint name="joint3" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 ${L2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-3.14159" upper="3.14159" effort="$(arg joint_effort)" velocity="$(arg joint_vel)"/>
    <dynamics damping="0.2" friction="0.0"/>
  </joint>

  <!-- Spherical wrist: all wrist joint origins coincide at the end of link3 -->
  <joint name="joint4" type="revolute">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="0 0 ${L3}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14159" upper="3.14159" effort="$(arg joint_effort)" velocity="$(arg joint_vel)"/>
    <dynamics damping="0.2" friction="0.0"/>
  </joint>

  <joint name="joint5" type="revolute">
    <parent link="link4"/>
    <child link="link5"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-3.14159" upper="3.14159" effort="$(arg joint_effort)" velocity="$(arg joint_vel)"/>
    <dynamics damping="0.2" friction="0.0"/>
  </joint>

  <joint name="joint6" type="revolute">
    <parent link="link5"/>
    <child link="link6"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14159" upper="3.14159" effort="$(arg joint_effort)" velocity="$(arg joint_vel)"/>
    <dynamics damping="0.2" friction="0.0"/>
  </joint>

  <!-- NOTE: tool0 REMOVED (no tool / no TCP) -->

  <!-- =========================
       ros2_control (gz_ros2_control)
       ========================= -->
  <ros2_control name="MyArmSystem" type="system">
    <hardware>
      <plugin>gz_ros2_control/GazeboSimSystem</plugin>
    </hardware>

    <joint name="joint1">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint2">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint3">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint4">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint5">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint6">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <!-- Gazebo plugin hook -->
  <gazebo>
    <plugin name="ign_ros2_control::IgnitionROS2ControlPlugin"
            filename="libign_ros2_control-system.so">
      <parameters>$(arg ros2_control_params)</parameters>
    </plugin>
  </gazebo>

</robot>
