<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="ur5e_simple">

  <xacro:arg name="ros2_control_params" default=""/>

  <!-- UR5e approximate dimensions (m) -->
  <xacro:arg name="d1" default="0.1625"/>
  <xacro:arg name="a2" default="0.425"/>
  <xacro:arg name="a3" default="0.3922"/>
  <xacro:arg name="d4" default="0.1333"/>
  <xacro:arg name="d5" default="0.0997"/>
  <xacro:arg name="d6" default="0.0996"/>

  <!-- Visual thickness -->
  <xacro:arg name="r_link" default="0.03"/>

  <!-- Base box -->
  <xacro:arg name="base_x" default="0.18"/>
  <xacro:arg name="base_y" default="0.18"/>
  <xacro:arg name="base_z" default="0.06"/>

  <!-- Masses -->
  <xacro:arg name="m_base" default="5.0"/>
  <xacro:arg name="m_link" default="0.8"/>   <!-- IMPORTANT: start light -->
  <xacro:arg name="m_tool" default="0.2"/>

  <!-- Limits -->
  <xacro:arg name="joint_vel" default="2.0"/>
  <xacro:arg name="joint_effort" default="50.0"/>

  <xacro:property name="r" value="$(arg r_link)"/>

  <!-- 
       Inertia macros
        -->
  <xacro:macro name="inertial_box" params="mass x y z">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="${mass*(y*y + z*z)/12.0}" ixy="0.0" ixz="0.0"
               iyy="${mass*(x*x + z*z)/12.0}" iyz="0.0"
               izz="${mass*(x*x + y*y)/12.0}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="inertial_cylinder_z" params="mass radius length">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="${mass*(3*radius*radius + length*length)/12.0}" ixy="0.0" ixz="0.0"
               iyy="${mass*(3*radius*radius + length*length)/12.0}" iyz="0.0"
               izz="${mass*(radius*radius)/2.0}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="inertial_cylinder_x" params="mass radius length">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="${mass*(radius*radius)/2.0}" ixy="0.0" ixz="0.0"
               iyy="${mass*(3*radius*radius + length*length)/12.0}" iyz="0.0"
               izz="${mass*(3*radius*radius + length*length)/12.0}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="inertial_cylinder_y" params="mass radius length">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="${mass*(3*radius*radius + length*length)/12.0}" ixy="0.0" ixz="0.0"
               iyy="${mass*(radius*radius)/2.0}" iyz="0.0"
               izz="${mass*(3*radius*radius + length*length)/12.0}"/>
    </inertial>
  </xacro:macro>

  <!-- 
       Materials
        -->
  <material name="dark"><color rgba="0.2 0.2 0.2 1.0"/></material>
  <material name="pale_blue"><color rgba="0.6 0.75 0.95 1.0"/></material>

  <!-- 
       World + base
        -->
  <link name="world"/>

  <joint name="world_to_base" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${$(arg base_z)/2.0}" rpy="0 0 0"/>
      <geometry><box size="$(arg base_x) $(arg base_y) $(arg base_z)"/></geometry>
      <material name="dark"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${$(arg base_z)/2.0}" rpy="0 0 0"/>
      <geometry><box size="$(arg base_x) $(arg base_y) $(arg base_z)"/></geometry>
    </collision>
    <xacro:inertial_box mass="$(arg m_base)" x="$(arg base_x)" y="$(arg base_y)" z="$(arg base_z)"/>
  </link>

  <!-- 
       Link macros (cylinders along x/y/z)
        -->
  <xacro:macro name="cyl_z" params="name length mass">
    <!-- sign: +1 or -1 to draw toward +Z or -Z -->
    <link name="${name}">
      <visual>
        <origin xyz="0 0 ${sign*length/2.0}" rpy="0 0 0"/>
        <geometry><cylinder radius="${r}" length="${length}"/></geometry>
        <material name="pale_blue"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${sign*length/2.0}" rpy="0 0 0"/>
        <geometry><cylinder radius="${r}" length="${length}"/></geometry>
      </collision>
      <xacro:inertial_cylinder_z mass="${mass}" radius="${r}" length="${length}"/>
    </link>
  </xacro:macro>

  <xacro:macro name="cyl_x" params="name length mass sign">
    <!-- sign: +1 or -1 to draw toward +X or -X -->
    <link name="${name}">
      <visual>
        <origin xyz="${sign*length/2.0} 0 0" rpy="0 1.57079632679 0"/>
        <geometry><cylinder radius="${r}" length="${length}"/></geometry>
        <material name="pale_blue"/>
      </visual>
      <collision>
        <origin xyz="${sign*length/2.0} 0 0" rpy="0 1.57079632679 0"/>
        <geometry><cylinder radius="${r}" length="${length}"/></geometry>
      </collision>
      <xacro:inertial_cylinder_x mass="${mass}" radius="${r}" length="${length}"/>
    </link>
  </xacro:macro>

  <xacro:macro name="cyl_y" params="name length mass sign">
    <!-- sign: +1 or -1 to draw toward +Y or -Y -->
    <link name="${name}">
      <visual>
        <origin xyz="0 ${sign*length/2.0} 0" rpy="1.57079632679 0 0"/>
        <geometry><cylinder radius="${r}" length="${length}"/></geometry>
        <material name="pale_blue"/>
      </visual>
      <collision>
        <origin xyz="0 ${sign*length/2.0} 0" rpy="1.57079632679 0 0"/>
        <geometry><cylinder radius="${r}" length="${length}"/></geometry>
      </collision>
      <xacro:inertial_cylinder_y mass="${mass}" radius="${r}" length="${length}"/>
    </link>
  </xacro:macro>

  <!-- Physical links -->
  <xacro:cyl_z name="link1" length="$(arg d1)" mass="$(arg m_link)"/>
  <xacro:cyl_x name="link2" length="$(arg a2)" mass="$(arg m_link)" sign="-1"/>
  <xacro:cyl_x name="link3" length="$(arg a3)" mass="$(arg m_link)" sign="-1"/>

  <!-- Wrist links oriented as you requested:
       link4 -> -Y, link5 -> -Z, link6 -> -Y -->
  <xacro:cyl_y name="link4" length="$(arg d4)" mass="$(arg m_link)" sign="-1"/>
  <xacro:cyl_z name="link5" length="$(arg d5)" mass="$(arg m_link)" sign="-1"/>
  <xacro:cyl_y name="link6" length="$(arg d6)" mass="$(arg m_link)" sign="-1"/>

  <!-- 
       Joints (simple, practical)
        -->

  <!-- joint1: base yaw -->
  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 $(arg base_z)" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-6.28318530718" upper="6.28318530718" effort="$(arg joint_effort)" velocity="$(arg joint_vel)"/>
    <dynamics damping="1.0" friction="0.0"/>
  </joint>

  <!-- joint2: shoulder pitch (about Y) at top of link1 -->
  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 $(arg d1)" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-6.28318530718" upper="6.28318530718" effort="$(arg joint_effort)" velocity="$(arg joint_vel)"/>
    <dynamics damping="2.0" friction="0.0"/>
  </joint>

  <!-- joint3: elbow pitch (about Y) at end of link2 (toward -X) -->
  <joint name="joint3" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="-$(arg a2) 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-6.28318530718" upper="6.28318530718" effort="$(arg joint_effort)" velocity="$(arg joint_vel)"/>
    <dynamics damping="2.0" friction="0.0"/>
  </joint>

  <!-- joint4: wrist1 (about Y) at end of link3 (toward -X) -->
  <joint name="joint4" type="revolute">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="-$(arg a3) 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-6.28318530718" upper="6.28318530718" effort="$(arg joint_effort)" velocity="$(arg joint_vel)"/>
    <dynamics damping="1.0" friction="0.0"/>
  </joint>

  <!-- joint5: wrist2 (about Z) at end of link4 (toward -Y) -->
  <joint name="joint5" type="revolute">
    <parent link="link4"/>
    <child link="link5"/>
    <origin xyz="0 -$(arg d4) 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-6.28318530718" upper="6.28318530718" effort="$(arg joint_effort)" velocity="$(arg joint_vel)"/>
    <dynamics damping="1.0" friction="0.0"/>
  </joint>

  <!-- joint6: wrist3 (about Y) at end of link5 (along +Z) -->
  <joint name="joint6" type="revolute">
    <parent link="link5"/>
    <child link="link6"/>
    <origin xyz="0 0 $(arg d5)" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-6.28318530718" upper="6.28318530718" effort="$(arg joint_effort)" velocity="$(arg joint_vel)"/>
    <dynamics damping="0.8" friction="0.0"/>
  </joint>

  <!-- 
       ros2_control (gz_ros2_control)
        -->
  <ros2_control name="MyArmSystem" type="system">
    <hardware>
      <plugin>gz_ros2_control/GazeboSimSystem</plugin>
    </hardware>

    <joint name="joint1">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint2">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint3">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint4">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint5">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint6">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <gazebo>
    <plugin name="ign_ros2_control::IgnitionROS2ControlPlugin"
            filename="libign_ros2_control-system.so">
      <parameters>$(arg ros2_control_params)</parameters>
    </plugin>
  </gazebo>

</robot>
